version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "morinokami"
    versioning-strategy: increase-if-necessary
    target-branch: "develop"
